Added clicking frame functionality
jcwillox/deeplabcut-webui pull request #4
Opened 2022-05-11 11:28 UTC by j-reno

Added a function clickFrame in ExtractView which takes in a string (in this case the image file name, e.g. img001.png), puts it through a regex check to remove everything but numbers (i.e. img001.png --> 001) and then changes the video player's frame to that new number by using the seekTo function. An on click event on the images in the carousel calls the function and supplies the image name as the parameter.

2022-05-11 13:19 UTC, jcwillox requested changes
Works great, there's just a couple of things for you to tweak before we merge this.

2022-05-11 13:19 UTC, jcwillox commented on frontend/src/views/ExtractView.vue
> +// Change player to frame of clicked of element
For consistency can you use lowercase for 'change', also I think it's meant to be 'on' instead of 'of'.
```suggestion
// change the player to the frame extracted from the images name
```

2022-05-11 13:19 UTC, jcwillox commented on frontend/src/views/ExtractView.vue
> +  const frameNumber = regex.exec(frameName);
The regex here is so simple you can just inline it, if it was more complex or used multiple times then I'd assign it to a variable and give it some intrinsic documentation e.g. `const regexDigit ...`
```suggestion
  const frameNumber = /\d+/.exec(frameName);
```

2022-05-11 13:19 UTC, jcwillox commented on frontend/src/views/ExtractView.vue
> +const clickFrame = frameName => {
You should provide the type for `frameName` here, vscode actually has a quick fix here to automatically infer type params from its usages.
```suggestion
const clickFrame = (frameName: string) => {
```

2022-05-12 03:38 UTC, j-reno commented
Committed the suggested changes - should be ready to review and merge.

2022-05-12 04:08 UTC, merged